apiVersion: v1
kind: service
metadata:
    name: {{ include "users-service.fullname" . }}
spec:
    selector:
        app: {{ include "users-service.name" . }} 
    ports:
        - port: {{ .Values.service.port }} 
          targetPort: 5000
    type: {{ .Values.service.type }}          
