apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb.fullname" . }}
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.rootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.rootPassword | quote }}
