apiVersion: v1
kind: PersistentVolumeClailm
metadata:
    name: {{ .Release.Name }}-mongodb
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.persistence.size }}
    storageClassName: {{ .Values.persistence.storageClass }}                
