apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "api-gateway.fullname" . }}-config
    labels:
        app: api-gateway
data:
    USERS_SERVICE_URL: "{{ .Values.env.USERS_SERVICE_URL }}"
    TASKS_SERVICE_URL: "{{ .Values.env.TASKS_SERVICE_URL }}"
    SECRET_URL:  "{{ .Values.env.SECRET_KEY }}"        


    
