{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
    name: {{ include "api-gateway.fullname" . }}
    labals:
        app: api-gateway
spec: 
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ include "api-gateway.fullname" . }}
    minReplicas: {{ .Values.autoscaling.minReplicas }}
    maxReplicas: {{ .Values.autoscaling.maxReplicas }}
    metrics:
        - type: Resource
          resources:
            name: cpu
            target:
                type: Utilization
                averageUtilization: {{ .Values.autoscaling.targetCPUUtizationPrecentage }}    
