grafana:
  enabled:
  adminPassword: "admin"
  service:
    type:
    port: 80
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - grafana.local
    paths:
      - /
prometheus:
  enabled: true          
