apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tasks-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tasks-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "tasks-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: {{ include "tasks-service.fullname" . }}
