apiVersion: v1
kind: Service
metadata:
  name: {{ include "tasks-service.fullname" . }}
spec:
  selector:
    app: {{ include "tasks-service.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  type: {{ .Values.service.type }}
