name: CI/CD - DTM App on EKS

on:
  push:
    branches: [ master ]

env:
  AWS_REGION: us-east-2
  CLUSTER_NAME: dtm-cluster
  REGISTRY: docker.io
  REPO: yakiradela
  KUBECONFIG: /home/runner/.kube/config

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    ####################################################################
    # שלב 1: Clone והרשאות AWS
    ####################################################################
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install unzip, AWS CLI, eksctl
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip curl
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    ####################################################################
    # שלב 2: Terraform - תשתיות (VPC, RDS, EKS)
    ####################################################################
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Terraform Bootstrap
      working-directory: distributed-task-manager/infra/boostrap
      run: |
        terraform init
        terraform apply -auto-approve -var="aws_region=${{ env.AWS_REGION }}"

    - name: Terraform Apply Infra
      working-directory: distributed-task-manager/infra
      run: |
        terraform init
        terraform apply -auto-approve -target=module.vpc -target=module.eks -target=module.rds

    ####################################################################
    # שלב 3: התקנת kubectl ו-helm
    ####################################################################
    - name: Install kubectl
      run: |
        KUBECTL_VERSION=$(curl -sL https://dl.k8s.io/release/stable.txt | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')
        curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Verify kubectl
      run: kubectl version --client

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Verify Helm
      run: helm version

    ####################################################################
    # שלב 4: התחברות לקלאסטר EKS
    ####################################################################
    - name: Update kubeconfig via eksctl
      run: |
        eksctl utils write-kubeconfig \
          --cluster="${CLUSTER_NAME}" \
          --region="${AWS_REGION}"

    - name: Verify Cluster Access
      run: |
        kubectl get nodes
        kubectl config current-context

    ####################################################################
    # שלב 5: Build & Push Docker Images
    ####################################################################
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Microservice Images
      run: |
        set -e
        for service in api-gateway tasks-service users-service; do
          echo "Building and pushing $service..."
          docker build -t $REGISTRY/$REPO/$service:latest ./distributed-task-manager/services/$service
          docker push $REGISTRY/$REPO/$service:latest
        done

    ####################################################################
    # שלב 6: פריסה עם Helm
    ####################################################################
    - name: Create Namespace (if not exists)
      run: |
        kubectl get namespace distributed-task-manager || \
        kubectl create namespace distributed-task-manager

    - name: Deploy Microservices with Helm
      run: |
        for service in api-gateway tasks-service users-service; do
          helm upgrade --install $service \
            ./charts/$service \
            --values ./charts/$service/values.yaml \
            --namespace distributed-task-manager
        done

    - name: Deploy MongoDB via Helm
      run: |
        helm upgrade --install mongodb ./charts/mongodb --namespace distributed-task-manager

    - name: Deploy Monitoring Stack (Grafana + Prometheus)
      run: |
        helm upgrade --install monitoring ./charts/grafana-prometheus --namespace distributed-task-manager

    ####################################################################
    # שלב 7: משאבי K8s נוספים
    ####################################################################
    - name: Apply Vault Agent Config
      run: kubectl apply -f distributed-task-manager/k8s/vault-agent-config.yaml

    - name: Apply Ingress Rules
      run: kubectl apply -f distributed-task-manager/k8s/ingress.yaml

    ####################################################################
    # שלב 8: בדיקות והדפסה
    ####################################################################
    - name: List Helm Releases
      run: helm list -n distributed-task-manager

    - name: Get All K8s Resources
      run: kubectl get all -n distributed-task-manager
